CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "Descriptions" (
    "Id" uuid NOT NULL,
    "Title" text NULL,
    "Summary" text NULL,
    CONSTRAINT "PK_Descriptions" PRIMARY KEY ("Id")
);

CREATE TABLE "Photos" (
    "Id" text NOT NULL,
    "Url" text NULL,
    CONSTRAINT "PK_Photos" PRIMARY KEY ("Id")
);

CREATE TABLE "Skills" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    CONSTRAINT "PK_Skills" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BulletPoint" (
    "Id" uuid NOT NULL,
    "Text" text NULL,
    "DescriptionId" uuid NULL,
    CONSTRAINT "PK_BulletPoint" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BulletPoint_Descriptions_DescriptionId" FOREIGN KEY ("DescriptionId") REFERENCES "Descriptions" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AppUserSkill" (
    "SkillsId" integer NOT NULL,
    "UsersId" text NOT NULL,
    CONSTRAINT "PK_AppUserSkill" PRIMARY KEY ("SkillsId", "UsersId"),
    CONSTRAINT "FK_AppUserSkill_Skills_SkillsId" FOREIGN KEY ("SkillsId") REFERENCES "Skills" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey")
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name")
);

CREATE TABLE "Certifications" (
    "Id" uuid NOT NULL,
    "Name" text NULL,
    "DateAcquired" timestamp without time zone NOT NULL,
    "AppUserId" text NULL,
    CONSTRAINT "PK_Certifications" PRIMARY KEY ("Id")
);

CREATE TABLE "EducationItems" (
    "Id" uuid NOT NULL,
    "FacilityName" text NULL,
    "FacilityLocation" text NULL,
    "FieldOfStudy" text NULL,
    "StudyingFrom" timestamp without time zone NOT NULL,
    "StudyingTo" timestamp without time zone NULL,
    "AppUserId" text NULL,
    CONSTRAINT "PK_EducationItems" PRIMARY KEY ("Id")
);

CREATE TABLE "EmploymentItems" (
    "Id" uuid NOT NULL,
    "EmployedFrom" timestamp without time zone NOT NULL,
    "EmployedTo" timestamp without time zone NULL,
    "DescriptionId" uuid NULL,
    "AppUserId" text NULL,
    CONSTRAINT "PK_EmploymentItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EmploymentItems_Descriptions_DescriptionId" FOREIGN KEY ("DescriptionId") REFERENCES "Descriptions" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "ExperienceItems" (
    "Id" uuid NOT NULL,
    "DescriptionId" uuid NULL,
    "AppUserId" text NULL,
    CONSTRAINT "PK_ExperienceItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExperienceItems_Descriptions_DescriptionId" FOREIGN KEY ("DescriptionId") REFERENCES "Descriptions" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "JobBids" (
    "Id" uuid NOT NULL,
    "BidderId" text NULL,
    "JobId" uuid NOT NULL,
    "Description" text NULL,
    "Fee" double precision NOT NULL,
    "AcceptedJobId" uuid NULL,
    CONSTRAINT "PK_JobBids" PRIMARY KEY ("Id")
);

CREATE TABLE "Jobs" (
    "Id" uuid NOT NULL,
    "EmployerId" text NULL,
    "Title" text NULL,
    "Description" text NULL,
    "CreationTime" timestamp without time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_Jobs" PRIMARY KEY ("Id")
);

CREATE TABLE "JobSkill" (
    "JobsId" uuid NOT NULL,
    "RequiredSkillsId" integer NOT NULL,
    CONSTRAINT "PK_JobSkill" PRIMARY KEY ("JobsId", "RequiredSkillsId"),
    CONSTRAINT "FK_JobSkill_Jobs_JobsId" FOREIGN KEY ("JobsId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_JobSkill_Skills_RequiredSkillsId" FOREIGN KEY ("RequiredSkillsId") REFERENCES "Skills" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PortfolioItems" (
    "Id" uuid NOT NULL,
    "Description" text NULL,
    "AppUserId" text NULL,
    CONSTRAINT "PK_PortfolioItems" PRIMARY KEY ("Id")
);

CREATE TABLE "Files" (
    "Id" text NOT NULL,
    "Url" text NULL,
    "ResourceType" text NULL,
    "JobId" uuid NULL,
    "PortfolioItemId" uuid NULL,
    CONSTRAINT "PK_Files" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Files_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Files_PortfolioItems_PortfolioItemId" FOREIGN KEY ("PortfolioItemId") REFERENCES "PortfolioItems" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "DisplayName" text NULL,
    "Bio" text NULL,
    "GithubProfileUrl" text NULL,
    "LinkedInProfileUrl" text NULL,
    "PhotoId" text NULL,
    "RatingSum" integer NOT NULL,
    "RatingCount" integer NOT NULL,
    "Location" text NULL,
    "CVId" text NULL,
    "CreationTime" timestamp without time zone NOT NULL,
    "UserName" character varying(256) NULL,
    "NormalizedUserName" character varying(256) NULL,
    "Email" character varying(256) NULL,
    "NormalizedEmail" character varying(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUsers_Files_CVId" FOREIGN KEY ("CVId") REFERENCES "Files" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AspNetUsers_Photos_PhotoId" FOREIGN KEY ("PhotoId") REFERENCES "Photos" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "RefreshToken" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "AppUserId" text NULL,
    "Token" text NULL,
    "Expires" timestamp without time zone NOT NULL,
    "Revoked" timestamp without time zone NULL,
    CONSTRAINT "PK_RefreshToken" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshToken_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Reviews" (
    "Id" uuid NOT NULL,
    "ReviewerId" text NULL,
    "RevieweeId" text NULL,
    "Rating" integer NOT NULL,
    "Description" text NULL,
    "CreationDate" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_AspNetUsers_RevieweeId" FOREIGN KEY ("RevieweeId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reviews_AspNetUsers_ReviewerId" FOREIGN KEY ("ReviewerId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_AppUserSkill_UsersId" ON "AppUserSkill" ("UsersId");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE INDEX "IX_AspNetUsers_CVId" ON "AspNetUsers" ("CVId");

CREATE INDEX "IX_AspNetUsers_PhotoId" ON "AspNetUsers" ("PhotoId");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE INDEX "IX_BulletPoint_DescriptionId" ON "BulletPoint" ("DescriptionId");

CREATE INDEX "IX_Certifications_AppUserId" ON "Certifications" ("AppUserId");

CREATE INDEX "IX_EducationItems_AppUserId" ON "EducationItems" ("AppUserId");

CREATE INDEX "IX_EmploymentItems_AppUserId" ON "EmploymentItems" ("AppUserId");

CREATE INDEX "IX_EmploymentItems_DescriptionId" ON "EmploymentItems" ("DescriptionId");

CREATE INDEX "IX_ExperienceItems_AppUserId" ON "ExperienceItems" ("AppUserId");

CREATE INDEX "IX_ExperienceItems_DescriptionId" ON "ExperienceItems" ("DescriptionId");

CREATE INDEX "IX_Files_JobId" ON "Files" ("JobId");

CREATE INDEX "IX_Files_PortfolioItemId" ON "Files" ("PortfolioItemId");

CREATE UNIQUE INDEX "IX_JobBids_AcceptedJobId" ON "JobBids" ("AcceptedJobId");

CREATE INDEX "IX_JobBids_BidderId" ON "JobBids" ("BidderId");

CREATE INDEX "IX_JobBids_JobId" ON "JobBids" ("JobId");

CREATE INDEX "IX_Jobs_EmployerId" ON "Jobs" ("EmployerId");

CREATE INDEX "IX_JobSkill_RequiredSkillsId" ON "JobSkill" ("RequiredSkillsId");

CREATE INDEX "IX_PortfolioItems_AppUserId" ON "PortfolioItems" ("AppUserId");

CREATE INDEX "IX_RefreshToken_AppUserId" ON "RefreshToken" ("AppUserId");

CREATE INDEX "IX_Reviews_RevieweeId" ON "Reviews" ("RevieweeId");

CREATE INDEX "IX_Reviews_ReviewerId" ON "Reviews" ("ReviewerId");

ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AppUserSkill" ADD CONSTRAINT "FK_AppUserSkill_AspNetUsers_UsersId" FOREIGN KEY ("UsersId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "Certifications" ADD CONSTRAINT "FK_Certifications_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "EducationItems" ADD CONSTRAINT "FK_EducationItems_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "EmploymentItems" ADD CONSTRAINT "FK_EmploymentItems_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "ExperienceItems" ADD CONSTRAINT "FK_ExperienceItems_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

ALTER TABLE "JobBids" ADD CONSTRAINT "FK_JobBids_AspNetUsers_BidderId" FOREIGN KEY ("BidderId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "JobBids" ADD CONSTRAINT "FK_JobBids_Jobs_AcceptedJobId" FOREIGN KEY ("AcceptedJobId") REFERENCES "Jobs" ("Id") ON DELETE RESTRICT;

ALTER TABLE "JobBids" ADD CONSTRAINT "FK_JobBids_Jobs_JobId" FOREIGN KEY ("JobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE;

ALTER TABLE "Jobs" ADD CONSTRAINT "FK_Jobs_AspNetUsers_EmployerId" FOREIGN KEY ("EmployerId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE;

ALTER TABLE "PortfolioItems" ADD CONSTRAINT "FK_PortfolioItems_AspNetUsers_AppUserId" FOREIGN KEY ("AppUserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211213150107_PGInitial', '5.0.4');

COMMIT;

START TRANSACTION;

ALTER TABLE "JobBids" DROP CONSTRAINT "FK_JobBids_Jobs_AcceptedJobId";

ALTER TABLE "Jobs" ADD "AcceptedJobBidId" uuid NULL;

ALTER TABLE "JobBids" ADD CONSTRAINT "FK_JobBids_Jobs_AcceptedJobId" FOREIGN KEY ("AcceptedJobId") REFERENCES "Jobs" ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211216181502_AccJobBidId', '5.0.4');

COMMIT;

